apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- k8s/myapp-deployment.yaml
- k8s/myapp-service.yaml

images:
- name: myapp # Replace with your actual container name
  newTag: 1.0
