apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: myapp
  name: myapp
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: myapp
  type: clusterIP
    
